ipn_validate_url : "https://www.sandbox.paypal.com/cgi-bin/webscr"
paypal_url : "https://sandbox.paypal.com/cgi-bin/webscr?"
paypal_email : "bcaff86-facilitator@hotmail.com"

production:
  ipn_validate_url : "https://www.paypal.com/cgi-bin/webscr"
  paypal_url : "https://paypal.com/cgi-bin/webscr?"
  paypal_email : "bostonhhh@aol.com"